name: 'Dark Patterns .NET and Pnpm Setup'
description: 'Installs .NET, PNPM, and Node, the Dark Patterns way'
inputs:
  node-version:
    description: Default node version
    default: '20'
outputs: {}
runs:
  using: 'composite'
  steps:
    # .NET install and cache
    - uses: actions/setup-dotnet@v4
      with:
        # The main version this project uses
        dotnet-version: '8.0.x'
        cache: true
        cache-dependency-path: ${{ (hashFiles('**/packages.lock.json') == '' && '**/*.csproj') || '**/packages.lock.json' }}

    # PNPM install and cache
    - uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Ensure Pnpm Store is set correctly
      # For some reason, at least when using nektosact, the store-dir is not correct by default.
      shell: sh
      run: |-
        if [ "$(pnpm config get store-dir)" != "$PNPM_HOME" ]; then
          echo "pnpm store not set to \$PNPM_HOME, setting now..."
          echo "pnpm config set store-dir \"$PNPM_HOME/../../.pnpm-cache\""
          pnpm config set store-dir "$PNPM_HOME/../../.pnpm-cache"
        fi

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'pnpm'

    - name: Install PNPM dependencies
      run: pnpm install --frozen-lockfile
      shell: pwsh

    - name: Restore dependencies
      run: dotnet restore --locked-mode
      shell: pwsh
